// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGLaEUiGivqMr3WhgHYtlYuWNK0hOl3VU',
    appId: '1:508069160076:web:61869590ae611f316687a9',
    messagingSenderId: '508069160076',
    projectId: 'my-app-e7fe8',
    authDomain: 'my-app-e7fe8.firebaseapp.com',
    storageBucket: 'my-app-e7fe8.firebasestorage.app',
    measurementId: 'G-R3TRY28NN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfmPa8rjK1u9ZAHjnbrEmiQHenk1o7ntg',
    appId: '1:508069160076:android:62a3b52a65a901f46687a9',
    messagingSenderId: '508069160076',
    projectId: 'my-app-e7fe8',
    storageBucket: 'my-app-e7fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB68Y-1aukWs5xuWsensZILdxhqFfZ3aFw',
    appId: '1:508069160076:ios:ff3dc519975e4fce6687a9',
    messagingSenderId: '508069160076',
    projectId: 'my-app-e7fe8',
    storageBucket: 'my-app-e7fe8.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB68Y-1aukWs5xuWsensZILdxhqFfZ3aFw',
    appId: '1:508069160076:ios:ff3dc519975e4fce6687a9',
    messagingSenderId: '508069160076',
    projectId: 'my-app-e7fe8',
    storageBucket: 'my-app-e7fe8.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGLaEUiGivqMr3WhgHYtlYuWNK0hOl3VU',
    appId: '1:508069160076:web:c332c50040ecb6a76687a9',
    messagingSenderId: '508069160076',
    projectId: 'my-app-e7fe8',
    authDomain: 'my-app-e7fe8.firebaseapp.com',
    storageBucket: 'my-app-e7fe8.firebasestorage.app',
    measurementId: 'G-JNN5P6SWBR',
  );
}
